config/routes.rb
PocketTimeline::Application.routes.draw do
  resources :questions

  resources :timelines do
    resources :events do
      member do
        post 'add'
      end
      collection do
        get 'search'
      end
    end
  end

  resources :events, only: [] do
    collection do
      get 'search'
    end
  end

  resources :events

  root 'home#index'
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true
  validate :date, presense: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :event
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  has_and_belongs_to_many :events, join_table: :timeline_events
end

app/models/timeline_event.rb
# class TimelineEvent < ActiveRecord::Base
#   # self.primary_keys = :timeline_id, :event_id
#   
#   has_one :timeline
#   has_one :event
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  skip_before_filter :verify_authenticity_token, if: :json_request?

protected
  def json_request?
    request.format.json?
  end

  def set_cacheable
    expires_in(5.minutes, public: true)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :add, :edit, :update, :destroy]
  before_action :set_timeline, only: [:search, :add, :new, :create, :index]
  before_action :set_cacheable, only: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = if @timeline.nil? then Event.all else @timeline.events end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/search
  # GET /timelines/1/events/search
  def search
    if params[:query]
      query = "%#{params[:query].downcase}%"
      @events = Event.where("lower(title) LIKE :query or lower(description) LIKE :query", :query => query)
    end

    respond_to do |format|
      format.html
      format.json { render 'events/index' }
    end
  end
  
  # POST /timelines/1/events/1/add
  def add
    @timeline.events.push @event
    respond_to do |format|
      format.html { redirect_to @timeline, notice: 'Event was added to timeline.' }
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    respond_to do |format|
      build_event
      if save_event_and_timeline
        format.html { redirect_to_event_or_timeline }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
    
    def set_timeline
      @timeline = Timeline.find(params[:timeline_id]) unless params[:timeline_id].nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :title, :description)
    end
    
    def build_event
      if @timeline
        @event = @timeline.events.build(event_params)
      else
        @event = Event.new(event_params)
      end
    end
    
    def save_event_and_timeline
      (@timeline ? @timeline.save : true) && @event.save
    end
    
    def redirect_to_event_or_timeline
      resource = @timeline ? @timeline : @event
      redirect_to resource, notice: 'Event was successfully created.'
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text, :event_id)
    end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :set_timeline, only: [:show, :edit, :update, :destroy]
  before_action :set_cacheable, only: [:index, :show]

  # GET /timelines
  # GET /timelines.json
  def index
    @timelines = Timeline.all
  end

  # GET /timelines/1
  # GET /timelines/1.json
  def show
  end

  # GET /timelines/new
  def new
    @timeline = Timeline.new
  end

  # GET /timelines/1/edit
  def edit
  end
  
  # POST /timelines
  # POST /timelines.json
  def create
    @timeline = Timeline.new(timeline_params)

    respond_to do |format|
      if @timeline.save
        format.html { redirect_to @timeline, notice: 'Timeline was successfully created.' }
        format.json { render action: 'show', status: :created, location: @timeline }
      else
        format.html { render action: 'new' }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timelines/1
  # PATCH/PUT /timelines/1.json
  def update
    respond_to do |format|
      if @timeline.update(timeline_params)
        format.html { redirect_to @timeline, notice: 'Timeline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timelines/1
  # DELETE /timelines/1.json
  def destroy
    @timeline.destroy
    respond_to do |format|
      format.html { redirect_to timelines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeline
      @timeline = Timeline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeline_params
      params.require(:timeline).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/events/_event.html.erb
<div class="event panel">
  <h6 class="clearfix">
    <%= event.date.to_formatted_s(:long) %>
    <div class="actions">
      <%= link_to 'View', event_path(event) %>
      <% if enable_add_event then %>
        <%= form_tag(add_timeline_event_url(@timeline, event), method: 'post') do -%>
          <%= submit_tag 'Add Event', :class => 'tiny button' %>
        <% end -%>
      <% else %>
        <%= link_to 'Edit', edit_event_path(event) %>
      <% end %>
    </div>
  </h6>
  <h5 class="event_title"><%= event.title %></h5>

</div>

app/views/events/_form.html.erb
<%= form_for([@timeline, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'shared/date_input_row', prefix: f.object_name %>
  <%= render 'shared/title_input_row', prefix: f.object_name %>
  <%= render 'shared/description_input_row', prefix: f.object_name %>

  <div class="row">
    <div class="large-12 columns">
      <%= f.submit :class => "small button action" %>
      <%= link_to 'Cancel', @event, :class => "small button cancel" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="content-full">
  <h1>Editing event</h1>
</div>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="content-full">
  <h1>Listing events</h1>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Title</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.date %></td>
          <td><%= event.title %></td>
          <td><%= event.description %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Event', new_event_path %>
</div>

app/views/events/new.html.erb
<div class="content-full">
  <h1>New event</h1>

  <%= render 'form' %>

  <%= link_to 'Back', events_path %>
</div>

app/views/events/search.html.erb
<div class="content-full">
  <h1>Search</h1>

  <%= form_tag('search', method: 'get') do -%>
    <div class="row collapse">
      <div class="large-11 small-10 columns">
        <input type="text" name="query" value="<%= params[:query] %>" autofocus />
      </div>
      <div class="large-1 small-2 columns">
        <%= submit_tag 'Search', :class => 'tiny postfix button' %>
      </div>
    </div>
  <% end -%>

  <% if @events then %>
    <% if @events.any? %>
      <% @events.each do |event| %>
        <%= render 'events/event', event: event, enable_add_event: !@timeline.nil? %>
      <% end %>
    <% else %>
      <p>No results found.</p>
    <% end %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="content-full event">
  <% unless notice.nil? %>
    <div class="large-12 columns">
      <div data-alert class="alert-box info">
        <p id="notice"><%= notice %></p>
        <a href="#" class="close">&times;</a>
      </div>
    </div>
  <% end %>
  
  <h3 class="subheader clearfix">
    <div class="actions">
      <%= link_to 'Edit', edit_event_path(@event) %>
    </div>
    <%= @event.date.to_formatted_s(:long) %>      
  </h3>
  <h1>
    <%= @event.title %>
  </h1>
  
  <p>
    <%= @event.description %>
  </p>
</div>

app/views/home/index.html.erb
<div class="content-full">
  <h1>Pocket Timeline</h1>
  
  <div class="panel">
    <ul>
      <li><%= link_to 'Timelines', timelines_path %></li>
      <li><%= link_to 'Events', events_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Pocket Timeline" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <div class="top-bar-container contain-to-grid fixed">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="/">Pocket Timeline</a></h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href=""><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="right">
            <li><a href="#about">About</a></li>
          </ul>
        </section>
      </nav>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Event</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.text %></td>
        <td><%= question.event %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<p>
  <strong>Event:</strong>
  <%= @question.event %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/shared/_date_input_row.html.erb
<div class="row">
  <div class="large-2 small-4 columns">
    <%= label(prefix, :year) %>
    <%= select_year(@event.date, :prefix => prefix, :field_name => 'date(1i)') %>
  </div>
  <div class="large-2 small-4 columns">
    <%= label(prefix, :month) %>
    <%= select_month(@event.date, :prefix => prefix, :field_name => 'date(2i)') %>
  </div>
  <div class="large-2 small-4 columns">
    <%= label(prefix, :day) %>
    <%= select_day(@event.date, :prefix => prefix, :field_name => 'date(3i)') %>
  </div>
  <div class="large-6 columns">
  </div>
</div>

app/views/shared/_description_input_row.html.erb
<div class="row">
  <div class="large-6 columns">
    <%= label(prefix, :description) %>
    <%= text_area(prefix, :description) %>
  </div>
</div>

app/views/shared/_title_input_row.html.erb
<div class="row">
  <div class="large-6 columns">
    <%= label(prefix, :title) %>
    <%= text_field(prefix, :title) %>
  </div>
</div>

app/views/timelines/_form.html.erb
<%= form_for(@timeline) do |f| %>
  <% if @timeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeline.errors.count, "error") %> prohibited this timeline from being saved:</h2>

      <ul>
      <% @timeline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timelines/edit.html.erb
<div class="content-full">
  <h1>Editing timeline</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @timeline %> |
  <%= link_to 'Back', timelines_path %>
</div>

app/views/timelines/index.html.erb
<div class="content-full">
  
  <h1>Listing timelines</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @timelines.each do |timeline| %>
        <tr>
          <td><%= timeline.title %></td>
          <td><%= timeline.description %></td>
          <td><%= link_to 'Show', timeline %></td>
          <td><%= link_to 'Edit', edit_timeline_path(timeline) %></td>
          <td><%= link_to 'Destroy', timeline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Timeline', new_timeline_path %>

</div>

app/views/timelines/new.html.erb
<div class="content-full">
  <h1>New timeline</h1>

  <%= render 'form' %>

  <%= link_to 'Back', timelines_path %>
</div>

app/views/timelines/show.html.erb
<div class="content-full">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @timeline.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @timeline.description %>
  </p>

  <p>
    <strong>Events:</strong>
  </p>

  <% @timeline.events.each do |event| %>
    <%= render 'events/event', event: event, enable_add_event: false %> 
  <% end %>

  <%= link_to 'Edit', edit_timeline_path(@timeline) %> |
  <%= link_to 'Back', timelines_path %>

  <br />

  <span>Add Event:</span>
  <%= link_to 'Create New', new_timeline_event_path(@timeline) %> |
  <%= link_to 'Add Existing', search_timeline_events_path(@timeline) %>
</div>